# Disable scp
scp:
  enabled: false
# set scp configuration in the other functions:
smf:
  services:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
    pcrf:
      enabled: false
amf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
ausf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
bsf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
nssf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
pcf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
udm:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
udr:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
upf:
  podAnnotations:
    sidecar.istio.io/inject: "false"
# Disable 4G functions
hss:
  enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false
# Disable webui
webui:
  enabled: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
  ingress:
    enabled: false
populate:
  enabled: true
  podAnnotations:
    sidecar.istio.io/inject: "false"
  initCommands:
  - for ue in {1..9}; do open5gs-dbctl add_ue_with_slice "99970000000000${ue}" 491BB1C6E1179AED538028AE7AD525B3 3B7FB099B3A6D16873B33F023B1679E9 internet 1 ffffff; done
    for ue in {10..99}; do open5gs-dbctl add_ue_with_slice "9997000000000${ue}" 491BB1C6E1179AED538028AE7AD525B3 3B7FB099B3A6D16873B33F023B1679E9 internet 1 ffffff; done
    for ue in {100..999}; do open5gs-dbctl add_ue_with_slice "9997000000000${ue}" 491BB1C6E1179AED538028AE7AD525B3 3B7FB099B3A6D16873B33F023B1679E9 internet 1 ffffff; done
    for ue in {1000..9999}; do open5gs-dbctl add_ue_with_slice "9997000000000${ue}" 491BB1C6E1179AED538028AE7AD525B3 3B7FB099B3A6D16873B33F023B1679E9 internet 1 ffffff; done
