# Disable scp
scp:
  enabled: false
# set scp configuration in the other functions:
smf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
    upf:
      pfcp:
        hostname: "192.168.82.4"
    pcrf:
      enabled: false
amf:
  commonAnnotations:
    loxilb.io/liveness: "yes"
    loxilb.io/lbmode: "fullnat"
    loxilb.io/staticIP: "192.168.82.252"
  services:
    ngap:
      type: LoadBalancer
      externalTrafficPolicy: Local
      loadBalancerClass: loxilb.io/loxilb
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
ausf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
bsf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
nssf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
pcf:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
udm:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
udr:
  config:
    sbi:
      client:
        scp:
          enabled: false
          uri: ""
        nrf:
          enabled: true
          uri: http://open5gs-nrf-sbi:7777
# Disable upf
upf:
  enabled: false
# Disable 4G functions
hss:
  enabled: false
mme:
  enabled: false
pcrf:
  enabled: false
sgwc:
  enabled: false
sgwu:
  enabled: false
# Disable webui
webui:
  enabled: false
  ingress:
    enabled: false
populate:
  enabled: true
  initCommands:
  - open5gs-dbctl add_ue_with_slice 999700000000001 491BB1C6E1179AED538028AE7AD525B3 3B7FB099B3A6D16873B33F023B1679E9 internet 1 ffffff
